openapi: 3.0.0
info:
  title: CoreComponent API
  version: 0.0.3
servers:
  - url: keddad.wtf
paths:
  /api/core/addface:
    post:
      summary: Отправить лицо на добавление. На фото должно быть только одно лицо
      operationId: addFaceTask
      parameters:
        - in: query
          name: append_face
          schema:
            type: boolean
            default: false
          description: Мержить ли трейты, если такое лицо уже есть в БД
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                face:
                  type: string
                  description: Base85 of file
                traits:
                  type: array
                  items:
                    $ref: "#/components/schemas/TraitInformation"
      responses:
        200:
          description: Обьект успешно принят на обработку
          

  /api/core/recface:
    get:
      summary: Отправить лицо на распознавание
      operationId: addFaceRecTask
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                face:
                  type: string
                  description: Base85 of file
      responses:
        200:
          description: Запрос выполнен успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: array
                    description: Matching faces if OK, otherwise empty
                    items:
                      $ref: "#/components/schemas/PersonInformation"

  /api/core/recvec:
    get:
      summary: Отправить вектор на распознавание
      operationId: addVecRecTask
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                face:
                  type: array
                  description: Вектор фич
                  items:
                    type: number
      responses:
        200:
          description: Запрос выполнен успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: array
                    description: Matching faces if OK, otherwise empty
                    items:
                      $ref: "#/components/schemas/PersonInformation"

components:
  schemas:
    TraitInformation:
      type: object
      description: Information about one trait
      properties:
        name:
          type: string
        options:
          type: array
          description: Варианты трейта (например, несколько ссылок на разные страницы в одной соцсети)
          items:
            type: string

    PersonInformation:
      type: object
      description: Информация о распознаном пользователе
      properties:
        traits:
          type: array
          items:
            $ref: "#/components/schemas/TraitInformation"
