version: "3"
services:
  ff_corecomp:
    restart: always
    build: ./corecomp
    depends_on:
      - ff_postgres
  ff_socialcomp:
    restart: always
    build: ./socialcomp
    depends_on:
        - ff_corecomp
  ff_postgres:
    restart: always
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=pass
  ff_nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ff_corecomp
      - ff_socialcomp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
