version: "3"
services:
  ff_corecomp:
    restart: always
    build: ./corecomp
    depends_on:
      - ff_mongodb
      - ff_redis
  ff_mongodb:
    restart: always
    image: mongo:latest
    environment:
      - AUTH=no
    ports:
      - "27017:27017"
  ff_redis:
    restart: always
    image: redis:rc-alpine3.11
    ports:
      - "6379:6379"
  ff_nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - ff_corecomp
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf

