openapi: 3.0.2
info:
  title: SocialComponent API
  version: 0.0.2
servers:
  - url: keddad.wtf
paths:
  /api/parse/{networkTag}/{id}:
    post:
      summary: Добавить в БД инфорамцию о пользователе с ID в социальной сети networkTag
      operationId: createTask
      parameters:
        - in: path
          name: networkTag
          schema:
            type: string
            enum: [VK, FB]
          required: true
        - in: path
          name: id
          schema:
            type: string
          required: true
        - in: query
          name: skip_existing
          schema:
            type: boolean
            default: false
          required: false
          description: Пропускать ли те страницы, которые уже есть в БД
      responses:
        200:
          description: Обьект успешно принят на обработку
