// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParseRequest struct {
	Links                []string `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Overwrite            bool     `protobuf:"varint,2,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseRequest) Reset()         { *m = ParseRequest{} }
func (m *ParseRequest) String() string { return proto.CompactTextString(m) }
func (*ParseRequest) ProtoMessage()    {}
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *ParseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseRequest.Unmarshal(m, b)
}
func (m *ParseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseRequest.Marshal(b, m, deterministic)
}
func (m *ParseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseRequest.Merge(m, src)
}
func (m *ParseRequest) XXX_Size() int {
	return xxx_messageInfo_ParseRequest.Size(m)
}
func (m *ParseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParseRequest proto.InternalMessageInfo

func (m *ParseRequest) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *ParseRequest) GetOverwrite() bool {
	if m != nil {
		return m.Overwrite
	}
	return false
}

type ParseByIdRequest struct {
	BeginId              int64    `protobuf:"varint,1,opt,name=begin_id,json=beginId,proto3" json:"begin_id,omitempty"`
	EndId                int64    `protobuf:"varint,2,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	Overwrite            bool     `protobuf:"varint,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseByIdRequest) Reset()         { *m = ParseByIdRequest{} }
func (m *ParseByIdRequest) String() string { return proto.CompactTextString(m) }
func (*ParseByIdRequest) ProtoMessage()    {}
func (*ParseByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ParseByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseByIdRequest.Unmarshal(m, b)
}
func (m *ParseByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseByIdRequest.Marshal(b, m, deterministic)
}
func (m *ParseByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseByIdRequest.Merge(m, src)
}
func (m *ParseByIdRequest) XXX_Size() int {
	return xxx_messageInfo_ParseByIdRequest.Size(m)
}
func (m *ParseByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParseByIdRequest proto.InternalMessageInfo

func (m *ParseByIdRequest) GetBeginId() int64 {
	if m != nil {
		return m.BeginId
	}
	return 0
}

func (m *ParseByIdRequest) GetEndId() int64 {
	if m != nil {
		return m.EndId
	}
	return 0
}

func (m *ParseByIdRequest) GetOverwrite() bool {
	if m != nil {
		return m.Overwrite
	}
	return false
}

type FaceRequest struct {
	FaceImage            []byte   `protobuf:"bytes,1,opt,name=face_image,json=faceImage,proto3" json:"face_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaceRequest) Reset()         { *m = FaceRequest{} }
func (m *FaceRequest) String() string { return proto.CompactTextString(m) }
func (*FaceRequest) ProtoMessage()    {}
func (*FaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *FaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceRequest.Unmarshal(m, b)
}
func (m *FaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceRequest.Marshal(b, m, deterministic)
}
func (m *FaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceRequest.Merge(m, src)
}
func (m *FaceRequest) XXX_Size() int {
	return xxx_messageInfo_FaceRequest.Size(m)
}
func (m *FaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FaceRequest proto.InternalMessageInfo

func (m *FaceRequest) GetFaceImage() []byte {
	if m != nil {
		return m.FaceImage
	}
	return nil
}

type FaceByLinkRequest struct {
	ImageUrl             string   `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaceByLinkRequest) Reset()         { *m = FaceByLinkRequest{} }
func (m *FaceByLinkRequest) String() string { return proto.CompactTextString(m) }
func (*FaceByLinkRequest) ProtoMessage()    {}
func (*FaceByLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *FaceByLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceByLinkRequest.Unmarshal(m, b)
}
func (m *FaceByLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceByLinkRequest.Marshal(b, m, deterministic)
}
func (m *FaceByLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceByLinkRequest.Merge(m, src)
}
func (m *FaceByLinkRequest) XXX_Size() int {
	return xxx_messageInfo_FaceByLinkRequest.Size(m)
}
func (m *FaceByLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceByLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FaceByLinkRequest proto.InternalMessageInfo

func (m *FaceByLinkRequest) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type FaceResponse struct {
	Faces                []*FaceResponse_FaceInfo `protobuf:"bytes,1,rep,name=faces,proto3" json:"faces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FaceResponse) Reset()         { *m = FaceResponse{} }
func (m *FaceResponse) String() string { return proto.CompactTextString(m) }
func (*FaceResponse) ProtoMessage()    {}
func (*FaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *FaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceResponse.Unmarshal(m, b)
}
func (m *FaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceResponse.Marshal(b, m, deterministic)
}
func (m *FaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceResponse.Merge(m, src)
}
func (m *FaceResponse) XXX_Size() int {
	return xxx_messageInfo_FaceResponse.Size(m)
}
func (m *FaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FaceResponse proto.InternalMessageInfo

func (m *FaceResponse) GetFaces() []*FaceResponse_FaceInfo {
	if m != nil {
		return m.Faces
	}
	return nil
}

type FaceResponse_MetaInfo struct {
	// Types that are valid to be assigned to Option:
	//	*FaceResponse_MetaInfo_StringInfo
	//	*FaceResponse_MetaInfo_IntInfo
	Option               isFaceResponse_MetaInfo_Option `protobuf_oneof:"option"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *FaceResponse_MetaInfo) Reset()         { *m = FaceResponse_MetaInfo{} }
func (m *FaceResponse_MetaInfo) String() string { return proto.CompactTextString(m) }
func (*FaceResponse_MetaInfo) ProtoMessage()    {}
func (*FaceResponse_MetaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4, 0}
}

func (m *FaceResponse_MetaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceResponse_MetaInfo.Unmarshal(m, b)
}
func (m *FaceResponse_MetaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceResponse_MetaInfo.Marshal(b, m, deterministic)
}
func (m *FaceResponse_MetaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceResponse_MetaInfo.Merge(m, src)
}
func (m *FaceResponse_MetaInfo) XXX_Size() int {
	return xxx_messageInfo_FaceResponse_MetaInfo.Size(m)
}
func (m *FaceResponse_MetaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceResponse_MetaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FaceResponse_MetaInfo proto.InternalMessageInfo

type isFaceResponse_MetaInfo_Option interface {
	isFaceResponse_MetaInfo_Option()
}

type FaceResponse_MetaInfo_StringInfo struct {
	StringInfo string `protobuf:"bytes,1,opt,name=string_info,json=stringInfo,proto3,oneof"`
}

type FaceResponse_MetaInfo_IntInfo struct {
	IntInfo int64 `protobuf:"varint,2,opt,name=int_info,json=intInfo,proto3,oneof"`
}

func (*FaceResponse_MetaInfo_StringInfo) isFaceResponse_MetaInfo_Option() {}

func (*FaceResponse_MetaInfo_IntInfo) isFaceResponse_MetaInfo_Option() {}

func (m *FaceResponse_MetaInfo) GetOption() isFaceResponse_MetaInfo_Option {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *FaceResponse_MetaInfo) GetStringInfo() string {
	if x, ok := m.GetOption().(*FaceResponse_MetaInfo_StringInfo); ok {
		return x.StringInfo
	}
	return ""
}

func (m *FaceResponse_MetaInfo) GetIntInfo() int64 {
	if x, ok := m.GetOption().(*FaceResponse_MetaInfo_IntInfo); ok {
		return x.IntInfo
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FaceResponse_MetaInfo) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FaceResponse_MetaInfo_StringInfo)(nil),
		(*FaceResponse_MetaInfo_IntInfo)(nil),
	}
}

type FaceResponse_FaceInfo struct {
	SocialLink           string                            `protobuf:"bytes,1,opt,name=social_link,json=socialLink,proto3" json:"social_link,omitempty"`
	Probability          float64                           `protobuf:"fixed64,2,opt,name=probability,proto3" json:"probability,omitempty"`
	Meta                 map[string]*FaceResponse_MetaInfo `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *FaceResponse_FaceInfo) Reset()         { *m = FaceResponse_FaceInfo{} }
func (m *FaceResponse_FaceInfo) String() string { return proto.CompactTextString(m) }
func (*FaceResponse_FaceInfo) ProtoMessage()    {}
func (*FaceResponse_FaceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4, 1}
}

func (m *FaceResponse_FaceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceResponse_FaceInfo.Unmarshal(m, b)
}
func (m *FaceResponse_FaceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceResponse_FaceInfo.Marshal(b, m, deterministic)
}
func (m *FaceResponse_FaceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceResponse_FaceInfo.Merge(m, src)
}
func (m *FaceResponse_FaceInfo) XXX_Size() int {
	return xxx_messageInfo_FaceResponse_FaceInfo.Size(m)
}
func (m *FaceResponse_FaceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceResponse_FaceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FaceResponse_FaceInfo proto.InternalMessageInfo

func (m *FaceResponse_FaceInfo) GetSocialLink() string {
	if m != nil {
		return m.SocialLink
	}
	return ""
}

func (m *FaceResponse_FaceInfo) GetProbability() float64 {
	if m != nil {
		return m.Probability
	}
	return 0
}

func (m *FaceResponse_FaceInfo) GetMeta() map[string]*FaceResponse_MetaInfo {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*ParseRequest)(nil), "ParseRequest")
	proto.RegisterType((*ParseByIdRequest)(nil), "ParseByIdRequest")
	proto.RegisterType((*FaceRequest)(nil), "FaceRequest")
	proto.RegisterType((*FaceByLinkRequest)(nil), "FaceByLinkRequest")
	proto.RegisterType((*FaceResponse)(nil), "FaceResponse")
	proto.RegisterType((*FaceResponse_MetaInfo)(nil), "FaceResponse.MetaInfo")
	proto.RegisterType((*FaceResponse_FaceInfo)(nil), "FaceResponse.FaceInfo")
	proto.RegisterMapType((map[string]*FaceResponse_MetaInfo)(nil), "FaceResponse.FaceInfo.MetaEntry")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x51, 0x6f, 0xd3, 0x3c,
	0x14, 0x5d, 0x9a, 0xaf, 0x5d, 0x72, 0xd3, 0x7d, 0x0c, 0x0b, 0xa6, 0x92, 0x82, 0x08, 0x7d, 0xa1,
	0x0f, 0x93, 0x87, 0x56, 0x90, 0x10, 0x8f, 0x95, 0x36, 0x2d, 0x12, 0x08, 0x64, 0xe0, 0x39, 0x72,
	0x1a, 0x37, 0xb2, 0x9a, 0xda, 0xc1, 0x71, 0x8b, 0xf2, 0x3f, 0x79, 0xe3, 0x17, 0xf0, 0x2f, 0x90,
	0xed, 0xa6, 0x74, 0x1b, 0x0f, 0xbc, 0xe5, 0x9e, 0x73, 0xee, 0x3d, 0xbe, 0x37, 0x07, 0x42, 0x5a,
	0x73, 0x5c, 0x2b, 0xa9, 0x65, 0x3c, 0x2e, 0xa5, 0x2c, 0x2b, 0x76, 0x61, 0xab, 0x7c, 0xb3, 0xbc,
	0x60, 0xeb, 0x5a, 0xb7, 0x8e, 0x9c, 0xcc, 0x61, 0xf8, 0x89, 0xaa, 0x86, 0x11, 0xf6, 0x6d, 0xc3,
	0x1a, 0x8d, 0x1e, 0x41, 0xbf, 0xe2, 0x62, 0xd5, 0x8c, 0xbc, 0xc4, 0x9f, 0x86, 0xc4, 0x15, 0xe8,
	0x29, 0x84, 0x72, 0xcb, 0xd4, 0x77, 0xc5, 0x35, 0x1b, 0xf5, 0x12, 0x6f, 0x1a, 0x90, 0x3f, 0xc0,
	0x24, 0x87, 0x53, 0x3b, 0x63, 0xde, 0xa6, 0x45, 0x37, 0xe7, 0x09, 0x04, 0x39, 0x2b, 0xb9, 0xc8,
	0x78, 0x31, 0xf2, 0x12, 0x6f, 0xea, 0x93, 0x63, 0x5b, 0xa7, 0x05, 0x7a, 0x0c, 0x03, 0x26, 0x0a,
	0x43, 0xf4, 0x2c, 0xd1, 0x67, 0xa2, 0x48, 0x8b, 0xdb, 0x1e, 0xfe, 0x5d, 0x8f, 0x73, 0x88, 0xae,
	0xe9, 0x62, 0xff, 0xcc, 0x67, 0x00, 0x4b, 0xba, 0x60, 0x19, 0x5f, 0xd3, 0x92, 0x59, 0x83, 0x21,
	0x09, 0x0d, 0x92, 0x1a, 0x60, 0xf2, 0x0a, 0x1e, 0x1a, 0xf5, 0xbc, 0x7d, 0xcf, 0xc5, 0xaa, 0xeb,
	0x19, 0x43, 0x68, 0xe5, 0xd9, 0x46, 0x55, 0xb6, 0x25, 0x24, 0x81, 0x05, 0xbe, 0xaa, 0x6a, 0xf2,
	0xab, 0x07, 0x43, 0x67, 0xd0, 0xd4, 0x52, 0x34, 0x0c, 0x9d, 0x43, 0xdf, 0xcc, 0x73, 0x87, 0x88,
	0x2e, 0xcf, 0xf0, 0x21, 0x6b, 0x8b, 0x54, 0x2c, 0x25, 0x71, 0xa2, 0xf8, 0x0b, 0x04, 0x1f, 0x98,
	0xa6, 0x06, 0x42, 0x2f, 0x20, 0x6a, 0xb4, 0xe2, 0xa2, 0xcc, 0xb8, 0x58, 0x4a, 0xe7, 0x74, 0x73,
	0x44, 0xc0, 0x81, 0x56, 0x32, 0x86, 0x80, 0x0b, 0xed, 0x78, 0x7b, 0x84, 0x9b, 0x23, 0x72, 0xcc,
	0x85, 0x36, 0xe4, 0x3c, 0x80, 0x81, 0xac, 0x35, 0x97, 0x22, 0xfe, 0xe1, 0x41, 0xd0, 0x39, 0xa1,
	0xe7, 0x10, 0x35, 0x72, 0xc1, 0x69, 0x95, 0x99, 0x7f, 0xb2, 0x5b, 0x00, 0x1c, 0x64, 0xd6, 0x44,
	0x09, 0x44, 0xb5, 0x92, 0x39, 0xcd, 0x79, 0xc5, 0x75, 0x6b, 0xe7, 0x7a, 0xe4, 0x10, 0x42, 0xaf,
	0xe1, 0xbf, 0x35, 0xd3, 0x74, 0xe4, 0xdb, 0x95, 0x92, 0xbf, 0xaf, 0x84, 0xcd, 0x22, 0x57, 0x42,
	0xab, 0x96, 0x58, 0x75, 0xfc, 0x11, 0xc2, 0x3d, 0x84, 0x4e, 0xc1, 0x5f, 0xb1, 0x76, 0xe7, 0x6e,
	0x3e, 0xcd, 0xa1, 0xb6, 0xb4, 0xda, 0xb8, 0x5c, 0xdc, 0x3b, 0x54, 0x77, 0x15, 0xe2, 0x44, 0xef,
	0x7a, 0x6f, 0xbd, 0xcb, 0x9f, 0x1e, 0x3c, 0xb8, 0xe6, 0xa2, 0x30, 0xc2, 0xcf, 0x4c, 0x6d, 0xf9,
	0x82, 0xa1, 0x37, 0xbb, 0x1c, 0xba, 0x5f, 0xd6, 0xa0, 0x13, 0x7c, 0x18, 0xcb, 0xf8, 0x0c, 0xbb,
	0x10, 0xe3, 0x2e, 0xc4, 0xf8, 0xca, 0x84, 0x18, 0xcd, 0x00, 0xf6, 0xd1, 0xfb, 0xe7, 0xa6, 0x97,
	0x10, 0x74, 0xf6, 0x68, 0x88, 0x0f, 0x62, 0x15, 0x9f, 0xdc, 0x7a, 0x3c, 0x9a, 0xc1, 0xff, 0x9d,
	0xd0, 0xbd, 0x0b, 0x21, 0x7c, 0x2f, 0x57, 0x77, 0x9a, 0xf2, 0x81, 0x75, 0x9b, 0xfd, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x29, 0xa0, 0x96, 0x8f, 0x82, 0x03, 0x00, 0x00,
}
