version: "3"
services:
  ff_corecomp:
    restart: always
    build: ./corecomp
    depends_on:
      - ff_postgres
  ff_socialcomp:
    restart: always
    build: ./socialcomp
    depends_on:
        - ff_corecomp
  ff_videocomp:
    restart: always
    build: ./videocomp
    depends_on:
        - ff_corecomp
  ff_bot:
    restart: always
    build: ./telbot
    depends_on:
      - ff_corecomp
      - ff_videocomp
    environment:
      - TOKEN=1399466852:AAEQx4VTO0LDOQLsoiZ-FyFYd87vKMGSkOs
  ff_postgres:
    restart: always
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=pass
  ff_nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ff_corecomp
      - ff_socialcomp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  ff_front:
    restart: always
    build: ./front
    depends_on:
      - ff_corecomp
      - ff_videocomp
