openapi: 3.0.0
info:
  title: CoreComponent API
  version: 1
servers:
  - url: keddad.wtf
paths:
  /api/core/addface:
    post:
      summary: Отправить лицо на добавление. На фото должно быть только одно лицо
      operationId: addFaceTask
      parameters:
        - in: query
          name: append_face
          schema:
            type: boolean
            default: false
          description: Мержить ли трейты, если такое лицо уже есть в БД
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                face:
                  type: string
                  description: Base85 of file
                traits:
                  type: object
                  additionalProperties:
                    type: array
                    items:
                      type: string
      responses:
        200:
          description: Обьект успешно принят на обработку

  /api/core/recface:
    post:
      summary: Отправить лицо на распознавание
      operationId: addFaceRecTask
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                face:
                  type: string
                  description: Base85 of file
      responses:
        200:
          description: Запрос выполнен успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    $ref: "#/components/schemas/PersonInformation"

  /api/core/recvec:
    post:
      summary: Отправить вектор на распознавание
      operationId: addVecRecTask
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                face:
                  type: array
                  description: Вектор фич
                  items:
                    type: number
      responses:
        200:
          description: Запрос выполнен успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    $ref: "#/components/schemas/PersonInformation"

components:
  schemas:
    PersonInformation:
      type: object
      description: Информация о распознаном пользователе
      properties:
        probability:
          type: number
        traits:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
